<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-LLLGMOJ" failures="2" tests="6" name="RetryMulitple" time="0.079" errors="0" timestamp="13 Sep 2022 03:15:38 GMT">
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.01">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test1(Test001.java:11)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.007">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.004">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="runTimeRetryfailedTc.Test001" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at runTimeRetryfailedTc.Test001.Test2(Test001.java:17)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMulitple -->
